---
- name: daemon reload
  systemd:
    daemon_reload: true

- name: restart dingo
  service:
    name: dingo
    state: restarted

- name: restart unbound
  service:
    name: unbound
    state: restarted
